In [1]:
pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are
        met:
        
            * Redistributions of source code must retain the above copyright
               notice, this list of conditions and the following disclaimer.
        
            * Redistributions in binary form must reproduce the above
               copyright notice, this list of conditions and the following
               disclaimer in the documentation and/or other materials provided
               with the distribution.
        
            * Neither the name of the NumPy Developers nor the names of any
               contributors may be used to endorse or promo

In [ ]:
import numpy as np
print(" successful")

 successful


In [6]:
import numpy as np
a = 44
val = np.array(a)
print(val)
print(type(val))
print(val.ndim)

44
<class 'numpy.ndarray'>
0


In [ ]:
#123
import numpy as np

list1 = [[10,20],[30,40],[50,60]]
val = np.array(list1)
print(val)

print(type(val))
print("dimension",val.ndim)
print("shape",val.shape)
print(val[1:])
print("transpose\n",val.T)

print("maximum",val.max())
print("minimum",val.min())
print("mean",val.mean())

sales=np.zeros(4)
print("zeros",sales)

sales=np.ones(5)
print("ones",sales)

sales = np.full(4,5)
print("full with 5s",sales)
print("flatten\n",val.flatten())


array = np.arange(10)
print(array)

print("mean =",np.average(array))
print("mean =",np.mean(array))
print("S.D=",np.std(array))
sd = np.sqrt(np.mean((array-np.mean(array))**2))
print("S.D=",sd)           
print("variance=",np.var(array))
print(np.median(array))

x = np.array([[0,3,4],[1,2,4],[3,4,5]])
print("shape",np.shape(x))
print("covariance=",np.cov(x))

x = np.array([1,3,5,7,8,9,10,15])
y = np.array([10,20,30,40,50,60,70,80])
print("covariance= \n",np.cov(x,y))
print("corelation = \n",np.corrcoef(x,y))

print("vstack= \n",np.vstack((x,y)))

print("roots= \n",np.roots(x))

print("dot product= ",np.dot(5,4))
vector_a = 2+3j
vector_b = 4+5j
print("dot = ",np.dot(vector_a,vector_b))

point1 = np.array((1,2,3))
point2 = np.array((1,1,1))

dist = np.linalg.norm(point1-point2)
print("Euclidean distance=",dist)

[[10 20]
 [30 40]
 [50 60]]
<class 'numpy.ndarray'>
dimension 2
shape (3, 2)
[[30 40]
 [50 60]]
transpose
 [[10 30 50]
 [20 40 60]]
maximum 60
minimum 10
mean 35.0
zeros [0. 0. 0. 0.]
ones [1. 1. 1. 1. 1.]
full with 5s [5 5 5 5]
flatten
 [10 20 30 40 50 60]
[0 1 2 3 4 5 6 7 8 9]
mean = 4.5
mean = 4.5
S.D= 2.8722813232690143
S.D= 2.8722813232690143
variance= 8.25
4.5
shape (3, 3)
covariance= [[4.33333333 2.83333333 2.        ]
 [2.83333333 2.33333333 1.5       ]
 [2.         1.5        1.        ]]
covariance= 
 [[ 19.07142857 104.28571429]
 [104.28571429 600.        ]]
corelation = 
 [[1.         0.97489441]
 [0.97489441 1.        ]]
vstack= 
 [[ 1  3  5  7  8  9 10 15]
 [10 20 30 40 50 60 70 80]]
roots= 
 [-1.78672856+0.j         -1.20921615+1.02304515j -1.20921615-1.02304515j
 -0.15868453+1.47489765j -0.15868453-1.47489765j  0.76126496+0.97013597j
  0.76126496-0.97013597j]
dot product=  20
dot =  (-7+22j)
Euclidean distance= 2.23606797749979


In [48]:
import numpy as np
l = [[10,20],[30,40]]
val = np.array(l)
print(val)
print(type(val))
print(val.ndim)
print(val[1][0])


[[10 20]
 [30 40]]
<class 'numpy.ndarray'>
2
30


In [80]:
import numpy as np
l = [[[10,20]],[[30,40]],[[50,60]]]
val = np.array(l)
print(val)
print(type(val))
print(val.ndim)
print(val[2][0][0])
print(val.T)

[[[10 20]]

 [[30 40]]

 [[50 60]]]
<class 'numpy.ndarray'>
3
50
[[[10 30 50]]

 [[20 40 60]]]


In [142]:
import numpy as np

list1 = [[10,20],[30,40],[50,60]]
val = np.array(list1)
print(val)

print(type(val))
print("dimension",val.ndim)
print("shape",val.shape)
print(val[1:])
print("transpose\n",val.T)

print("maximum",val.max())
print("minimum",val.min())
print("mean",val.mean())

sales=np.zeros(4)
print("zeros",sales)

sales=np.ones(5)
print("ones",sales)

sales = np.full(4,5)
print("full with 5s",sales)
print("flatten\n",val.flatten())


array = np.arange(10)
print(array)

print("mean =",np.average(array))
print("mean =",np.mean(array))
print("S.D=",np.std(array))
sd = np.sqrt(np.mean((array-np.mean(array))**2))
print("S.D=",sd)           
print("variance=",np.var(array))
print(np.median(array))

x = np.array([[0,3,4],[1,2,4],[3,4,5]])
print("shape",np.shape(x))
print("covariance=",np.cov(x))

x = np.array([1,3,5,7,8,9,10,15])
y = np.array([10,20,30,40,50,60,70,80])
print("covariance= \n",np.cov(x,y))
print("corelation = \n",np.corrcoef(x,y))

print("vstack= \n",np.vstack((x,y)))

print("roots= \n",np.roots(x))

print("dot product= ",np.dot(5,4))
vector_a = 2+3j
vector_b = 4+5j
print("dot = ",np.dot(vector_a,vector_b))

point1 = np.array((1,2,3))
point2 = np.array((1,1,1))

dist = np.linalg.norm(point1-point2)
print("Euclidean distance=",dist)

[[10 20]
 [30 40]
 [50 60]]
<class 'numpy.ndarray'>
dimension 2
shape (3, 2)
[[30 40]
 [50 60]]
transpose
 [[10 30 50]
 [20 40 60]]
maximum 60
minimum 10
mean 35.0
zeros [0. 0. 0. 0.]
ones [1. 1. 1. 1. 1.]
full with 5s [5 5 5 5]
flatten
 [10 20 30 40 50 60]
[0 1 2 3 4 5 6 7 8 9]
mean = 4.5
mean = 4.5
S.D= 2.8722813232690143
S.D= 2.8722813232690143
variance= 8.25
4.5
shape (3, 3)
covariance= [[4.33333333 2.83333333 2.        ]
 [2.83333333 2.33333333 1.5       ]
 [2.         1.5        1.        ]]
covariance= 
 [[ 19.07142857 104.28571429]
 [104.28571429 600.        ]]
corelation = 
 [[1.         0.97489441]
 [0.97489441 1.        ]]
vstack= 
 [[ 1  3  5  7  8  9 10 15]
 [10 20 30 40 50 60 70 80]]
roots= 
 [-1.78672856+0.j         -1.20921615+1.02304515j -1.20921615-1.02304515j
 -0.15868453+1.47489765j -0.15868453-1.47489765j  0.76126496+0.97013597j
  0.76126496-0.97013597j]
dot product=  20
dot =  (-7+22j)
Euclidean distance= 2.23606797749979
